server:
  port: 8001

spring:
  application:
    name: spring-cloud-aply

#注册中心指向start
eureka:
  instance:
    instance-id: spring-cloud-aply
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka/